services:
  minio-lakehouse:
    image: minio/minio
    container_name: miniolakehouse
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: mypassword
    volumes:
      - ./data-minio:/data
    command: server /data --console-address ":9001"

    networks:
      - data_network

  awscli:
    image: amazon/aws-cli
    container_name: awscli
    hostname: awscli
    depends_on:
      - minio-lakehouse
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: mypassword
    entrypoint: ["tail", "-f", "/dev/null"]

    networks:
      - data_network


networks:
  data_network:
    external: true
