#networks:
  # hadoop_net:
  #   driver: bridge


networks:
  data_network:
    driver: bridge
    name: data_network
    external: true 

services:
  client:
    image: client
    container_name: client
    hostname: quochuy-client
    ports:
      - "4040:4040"

      
    volumes:
      - ./data:/home/hadoopquochuy/data
      - ./scripts:/home/hadoopquochuy/scripts


    networks:
      - data_network
    command: /bin/bash -c "service ssh start; tail -f /dev/null"

  master:
    image: master-official
    container_name: master-huy
    hostname: quochuy-master
    volumes:
      - hdfs_namenode:/home/hadoopquochuy/hadoop/hadoop_data/hdfs/namenode
      - ./scripts:/home/hadoopquochuy/scripts

    ports:
      - "9004:9004"
      - "9870:9870"

    networks:
      - data_network
    command: /bin/bash -c "service ssh start; tail -f /dev/null"
    
volumes:
  hdfs_namenode:
